[NN_dims]
set_h_dim = 64
set_out_dim = 64
d2v_layers = [ 4, 2, 4,]
pos_depth = 2
pos_enc_dim = 15
load_d2v = true
freeze_d2v = false
model_load = "model_main"
weight_hid_dim = 64
gen_layers = 2
gat_heads = 2
gat_layers = 2
gat_hid_dim = 128
gat_out_dim = 16
reparam_weight = false
reparam_pos_enc = false
weight_bias = "off"
pos_enc_bias = "zero"
norm_lin = true
norm_weights = true
learn_norm = true
gat_in_dim = 16

[Optim]
lr = 0.0005

[DL_params]
bs = 3
num_rows = 15
num_targets = 5
ds_group = -1
balance_train = true
one_v_all = true

[Settings]
num_epochs = 21
val_duration = 100
val_interval = 2000
dataset = "total"
