[NN_dims]
pos_enc_dim = 7
set_h_dim = 64
set_out_dim = 32
weight_hid_dim = 64
gat_heads = 2
gat_hid_dim = 128
gat_out_dim = 16
d2v_layers = [ 5, 2, 5, 2,]
gen_layers = 2
gat_layers = 3
reparam_weight = false
reparam_pos_enc = false
gat_in_dim = 8

[Optim]
lr = 0.0003

[DL_params]
bs = 3
num_rows = 10
num_targets = 10
flip = false
num_cols = 8
num_cols_range = [ 2, 10,]
num_models = -1

[Settings]
num_epochs = 10000
save_dir = ""
val_duration = 200
val_interval = 2000
dataset = "adult"

[MLP_DL_params]
noise_std = 0.3
pre_sample_weights = false
hidden_dim = 3
num_causes = 2
num_layers = 3
is_causal = true
dropout_prob = 0.5
init_std = 1
pre_sample_causes = false
in_clique = true
is_effect = true
sort_features = true
