[NN_dims]
pos_enc_dim = 3
set_h_dim = 64
set_out_dim = 32
weight_hid_dim = 64
gat_heads = 2
gat_hid_dim = 128
gat_out_dim = 16
d2v_layers = [ 3, 2, 3, 2,]
gen_layers = 2
gat_layers = 2
reparam_weight = false
reparam_pos_enc = false
weight_bias = "zero"
pos_enc_bias = "zero"
load_d2v = true
freeze_d2v = false
gat_in_dim = 4

[Optim]
lr = 0.0003

[DL_params]
bs = 3
num_rows = 10
num_targets = 5
flip = false

[Settings]
num_epochs = 10000
val_duration = 400
val_interval = 2000
dataset = "total"

[MLP_DL_params]
noise_std = 0.3
pre_sample_weights = false
hidden_dim = 3
num_causes = 2
num_layers = 3
is_causal = true
dropout_prob = 0.5
init_std = 1
pre_sample_causes = false
in_clique = true
is_effect = true
sort_features = true
