[NN_dims]
set_h_dim = 64
set_out_dim = 64
d2v_layers = [ 4, 2, 4,]
pos_depth = 2
pos_enc_dim = 15
load_d2v = true
freeze_d2v = false
model_load = "model_3"
weight_hid_dim = 64
gen_layers = 1
gat_heads = 2
gat_layers = 2
gat_hid_dim = 128
gat_out_dim = 16
reparam_weight = false
reparam_pos_enc = false
weight_bias = "off"
pos_enc_bias = "zero"
norm_lin = true
norm_weights = true
learn_norm = true
gat_in_dim = 16

[Optim]
lr = 0.0005
eps = 0.0003

[DL_params]
bs = 3
num_rows = 16
num_targets = 5
ds_group = -1
test_data_names = [ "statlog-heart", "horse-colic", "fertility", "post-operative",]
train_data_names = [ "dermatology", "hepatitis", "lung-cancer", "breast-cancer-wisc-prog", "cardiotocography-3clases", "breast-tissue", "statlog-heart", "acute-inflammation", "breast-cancer-wisc-diag", "parkinsons", "arrhythmia", "echocardiogram", "mammographic", "vertebral-column-2clases", "heart-cleveland", "post-operative", "lymphography", "primary-tumor", "heart-hungarian", "spect", "breast-cancer", "horse-colic", "heart-va", "spectf", "heart-switzerland", "fertility", "ilpd-indian-liver",]
binarise = false

[Settings]
num_epochs = 601
val_duration = 100
val_interval = 2000
dataset = "total"
