[NN_dims]
set_h_dim = 64
set_out_dim = 64
d2v_layers = [ 3, 2, 3,]
pos_depth = 2
pos_enc_dim = 15
load_d2v = false
freeze_d2v = false
model_load = "model_3"
weight_hid_dim = 64
gen_layers = 1
gat_heads = 2
gat_layers = 2
gat_hid_dim = 128
gat_out_dim = 16
reparam_weight = false
reparam_pos_enc = false
weight_bias = "off"
pos_enc_bias = "zero"
norm_lin = true
norm_weights = true
learn_norm = true
gat_in_dim = 16

[Optim]
lr = 0.0005
eps = 0.0003

[DL_params]
bs = 3
num_rows = 5
num_targets = 5
ds_group = -1
balance_train = true
one_v_all = true
num_split = "0"
num_cols = [ 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,]
train_data_names = [ "dermatology", "hepatitis", "lung-cancer", "breast-cancer-wisc-prog", "cardiotocography-3clases", "breast-tissue", "statlog-heart", "thyroid", "acute-inflammation", "breast-cancer-wisc-diag", "parkinsons", "arrhythmia", "echocardiogram", "mammographic", "heart-cleveland", "lymphography", "blood", "primary-tumor", "heart-hungarian", "acute-nephritis", "spect", "heart-va", "spectf", "heart-switzerland", "fertility", "breast-cancer-wisc", "ilpd-indian-liver",]
test_data_names = [ "post-operative", "breast-cancer", "horse-colic", "vertebral-column-2clases",]
shuffle_cols = true

[Settings]
num_epochs = 50
val_duration = 100
val_interval = 1000
dataset = "mydata"
