[NN_dims]
pos_enc_dim = 3
set_h_dim = 64
set_out_dim = 32
weight_hid_dim = 64
gat_heads = 2
gat_hid_dim = 128
gat_in_dim = 4
gat_out_dim = 16

[LR]
meta_lr = 0.0003
target_lr = 0.0003

[DL_params]
bs = 2
num_rows = 10
num_targets = 5
flip = false
